# Some settings need to be re-applied on every load.

# Aliases.
alias vim="nvim"
alias ra="rcmpy apply"

###############################################################################

# Settings for bash. Only load this once.
if [ "$BASHRC_LOADED" ]; then
	return
fi
export BASHRC_LOADED=1
