# Lines configured by zsh-newuser-install
# HISTFILE=~/.histfile
# HISTSIZE=1000
# SAVEHIST=1000
# setopt autocd extendedglob nomatch notify
# unsetopt beep
# bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
# zstyle :compinstall filename ~/.zshrc

# autoload -Uz compinit
# compinit
# End of lines added by compinstall

THIRD_PARTY=$HOME/third-party

# Path to your oh-my-zsh installation.
export ZSH="$THIRD_PARTY/ohmyzsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes.
ZSH_THEME="steeef"

plugins=(git command-not-found)

if [ -d "$HOME/third-party/fzf" ]; then
	plugins+=(fzf)
	export FZF_BASE="$HOME/third-party/fzf"
fi

SCRIPTS=("$HOME/.shrc")
SCRIPTS+=("$THIRD_PARTY/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh")
SCRIPTS+=("$ZSH/oh-my-zsh.sh")

for _SCRIPT in "${SCRIPTS[@]}"; do
	if [ -f "$_SCRIPT" ]; then
		. "$_SCRIPT"
	fi
done
unset SCRIPTS
unset _SCRIPT

bindkey -v
