# Lines configured by zsh-newuser-install
# HISTFILE=~/.histfile
# HISTSIZE=1000
# SAVEHIST=1000
# setopt autocd extendedglob nomatch notify
# unsetopt beep
# bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
# zstyle :compinstall filename ~/.zshrc

# autoload -Uz compinit
# compinit
# End of lines added by compinstall

# Path to your oh-my-zsh installation.
export ZSH="$HOME/third-party/ohmyzsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes.
ZSH_THEME="steeef"

plugins=(git tmux sudo command-not-found)

if [ -d "$HOME/third-party/fzf" ]; then
	plugins+=(fzf)
	export FZF_BASE="$HOME/third-party/fzf"
fi

source ~/.shrc
source $ZSH/oh-my-zsh.sh

bindkey -v
