---
name: yamllint

on:  # yamllint disable-line
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version: ["3.11"]
        system: [ubuntu-latest]

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}

      - run: pip${{matrix.python-version}} install yamllint

      - run: ./ci/lint.sh

      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: ci
